/**
 * Simply Connect — Agent Performance Dashboard
 * Apps Script JSON API
 *
 * Deploy: Extensions → Apps Script → paste this whole file → Deploy →
 * New deployment → Web app → Execute as Me → Who has access: Anyone →
 * Deploy → copy the /exec URL into the dashboard's API Setup tab
 * (or js/config.js for a shared deploy).
 *
 * GET <url>?days=90            → last 90 days of both tabs, as JSON
 * GET <url>?days=90&key=xxxx   → same, but only if SHARED_SECRET matches
 */

// ───────────────────────── CONFIG ─────────────────────────
var CONFIG = {
  CALLS_SHEET_NAME: 'Calls Data',
  SALES_SHEET_NAME: 'sales Data',

  // Leave blank to allow anyone with the URL to read the API.
  // Set a string to require ?key=that-string on every request.
  SHARED_SECRET: '',

  // How many days of history to return if ?days= isn't passed.
  DEFAULT_DAYS: 90,

  // How long (seconds) to cache a response for a given days value.
  CACHE_SECONDS: 300,

  // Columns from "sales Data" that are safe to send to the browser.
  // Everything NOT in this list (customer name/email/phone/address/
  // account numbers/PINs/security questions/etc.) is dropped before
  // the response ever leaves the server. Add a column name here only
  // if you deliberately want it visible on the public dashboard.
  SALES_FIELDS_ALLOWED: [
    'Date', 'Timestamp', 'gRPCampaign Number', 'Agent Name', 'Closer Name',
    'State', 'Provider', 'Services', "RGU's", 'Installation Type',
    'Installation Date', 'Installation Time', 'Team',
    'Sales Call/Non Sales Call', 'Sale Processed', 'Current Provider',
    'Lead Generated by (If Any)', 'Call Received from Queue Name',
    'Any Third Party Streaming Services Sold', 'Total Points'
  ],

  // Calls Data columns sent to the browser. Calls Data has no direct
  // customer PII (the caller's phone number is the only sensitive-ish
  // field), so it's excluded here too.
  CALLS_FIELDS_ALLOWED: [
    'Call Center Name', 'Date', 'Time Frame', 'Agent Name', 'Call Result',
    'Wait Time', 'Talk Time', 'Hold Time', 'Wrap Up Time',
    'Disposition Codes'
  ]
};

// ───────────────────────── ENTRY POINT ─────────────────────────
function doGet(e) {
  try {
    var params = (e && e.parameter) || {};

    if (CONFIG.SHARED_SECRET && params.key !== CONFIG.SHARED_SECRET) {
      return jsonOut({ error: 'Unauthorized' }, 401);
    }

    var days = parseInt(params.days, 10);
    if (!days || days <= 0) days = CONFIG.DEFAULT_DAYS;
    days = Math.min(days, 3650);

    var cacheKey = 'dash_v1_' + days;
    var cache = CacheService.getScriptCache();
    var cached = cache.get(cacheKey);
    if (cached) {
      return jsonOut(JSON.parse(cached));
    }

    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var callsSheet = ss.getSheetByName(CONFIG.CALLS_SHEET_NAME);
    var salesSheet = ss.getSheetByName(CONFIG.SALES_SHEET_NAME);
    if (!callsSheet) throw new Error('Sheet not found: ' + CONFIG.CALLS_SHEET_NAME);
    if (!salesSheet) throw new Error('Sheet not found: ' + CONFIG.SALES_SHEET_NAME);

    var cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - days);
    cutoff.setHours(0, 0, 0, 0);

    var callsResult = readSheet(callsSheet, cutoff, CONFIG.CALLS_FIELDS_ALLOWED);
    var salesResult = readSheet(salesSheet, cutoff, CONFIG.SALES_FIELDS_ALLOWED);

    // Normalize campaign naming so Calls Data's "Call Center Name"
    // (e.g. "Group 44 Sales", "Group 44 CS") lines up with sales
    // Data's "gRPCampaign Number" (e.g. "Group 44").
    callsResult.rows.forEach(function (row) {
      row['Campaign'] = normalizeCampaign(row['Call Center Name']);
    });
    salesResult.rows.forEach(function (row) {
      row['Campaign'] = normalizeCampaign(row['gRPCampaign Number']);
    });

    var payload = {
      generatedAt: new Date().toISOString(),
      rangeDays: days,
      meta: {
        callsRows: callsResult.rows.length,
        salesRows: salesResult.rows.length,
        lastCallDate: callsResult.lastDate,
        lastSaleDate: salesResult.lastDate
      },
      calls: callsResult.rows,
      sales: salesResult.rows
    };

    cache.put(cacheKey, JSON.stringify(payload), CONFIG.CACHE_SECONDS);
    return jsonOut(payload);
  } catch (err) {
    return jsonOut({ error: String(err && err.message ? err.message : err) }, 500);
  }
}

// ───────────────────────── HELPERS ─────────────────────────

function readSheet(sheet, cutoffDate, allowedFields) {
  var values = sheet.getDataRange().getValues();
  var headers = values[0];
  var dateCol = headers.indexOf('Date');
  var rows = [];
  var lastDate = null;

  for (var r = 1; r < values.length; r++) {
    var raw = values[r];
    var rowDate = raw[dateCol];
    if (!(rowDate instanceof Date)) continue;
    if (rowDate < cutoffDate) continue;

    var row = {};
    for (var c = 0; c < headers.length; c++) {
      var col = headers[c];
      if (allowedFields.indexOf(col) === -1) continue;
      row[col] = serializeCell(col, raw[c]);
    }
    rows.push(row);

    if (!lastDate || rowDate > lastDate) lastDate = rowDate;
  }

  return {
    rows: rows,
    lastDate: lastDate ? Utilities.formatDate(lastDate, Session.getScriptTimeZone(), 'yyyy-MM-dd') : null
  };
}

// Converts a raw cell value into something JSON-friendly. Duration
// columns (Wait/Talk/Hold/Wrap Up Time) come back from Sheets as a
// Date at the 1899-12-30 epoch with only the time-of-day meaningful —
// this turns those into plain seconds so the dashboard can just add
// numbers instead of parsing dates in the browser.
var DURATION_FIELDS = ['Wait Time', 'Talk Time', 'Hold Time', 'Wrap Up Time'];

function serializeCell(col, value) {
  if (value instanceof Date) {
    if (DURATION_FIELDS.indexOf(col) !== -1) {
      return value.getHours() * 3600 + value.getMinutes() * 60 + value.getSeconds();
    }
    if (col === 'Date' || col === 'Installation Date') {
      return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
    }
    return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');
  }
  if (value === '' ) return null;
  return value;
}

function normalizeCampaign(name) {
  if (!name) return 'Unassigned';
  var s = String(name).trim();
  var m = s.match(/^Group\s*\d+/i);
  if (m) return m[0].replace(/\s+/g, ' ').replace(/^group/i, 'Group');
  return s;
}

function jsonOut(obj, statusCode) {
  var out = ContentService.createTextOutput(JSON.stringify(obj));
  out.setMimeType(ContentService.MimeType.JSON);
  return out;
}
